# Generated by Django 5.1 on 2024-08-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='products',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='user',
        ),
        migrations.AddField(
            model_name='buy',
            name='buy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
